name: byfix
description: BYFIX

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_circle_color_picker: ^0.3.0
  flutter_bluetooth_serial: ^0.4.0
  flutter_advanced_drawer: ^1.2.3+1
  carousel_slider: ^4.0.0
  line_icons: ^2.0.1
  intl: ^0.17.0
  http: ^0.13.4
  provider: ^6.0.1
  pull_to_refresh: ^2.0.0
  loader_overlay: ^2.0.2+1
  skeleton_loader: ^2.0.0+4
  simple_shadow: ^0.2.0
  sliding_up_panel: ^2.0.0+1
  interactiveviewer_gallery: ^0.6.0
  flutter_widget_from_html_core: ^0.8.1
  percent_indicator: ^3.4.0
  shared_preferences: ^2.0.8
  iyzico: ^0.1.1+3
  crypto: ^3.0.1
  art_sweetalert: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
